In [1]:
import numpy as np
import pandas as pd

In [9]:
# create a numpy 1-D array by using a python list

python_list = [1,2,3,4]
np_array = np.array(python_list)
np_array

# create a numpy 2-D array by using a python list of lists
python_2dlist = [[1,2,3,4], [5,6,7,8]]
np_2darray = np.array(python_2dlist)
np_2darray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# use arange() and reshape() function to create a multi-dimension array?

#arange() used to create a 1D, 2D, 3D array. e.g., np.array(4) creates [1,2,3,4]
#reshape() used to change the shape of a numpy array
array = np.arange(8).reshape(4,2)
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### Problem 1: Compute the min/max for each row for a NumPy 2D array

In [3]:
np.random.seed(10)

a = np.random.randint(1, 10, [5, 3])  # return random integer from 1 to 10, the size of the array is 5x3

# use apply_along_axis to use a specified function along with !D slices of the input array
solution = np.apply_along_axis(lambda x: np.min(x) / np.max(x), arr=a, axis=1)  # since row so axis =1

print(solution)

[0.2        0.11111111 0.11111111 0.2        0.55555556]


### Problem 2: find all occurrences of an Element in a list

In [4]:
my_list = [1, 2, 3, 1, 2, 4, 5, 6, 3, 2, 1]

indices = [i for i, x in enumerate(my_list) if
           x == 5]  # iterator enumerate(my_list) yields pairs (index, item) for each item in the list.
print(indices)

values = np.array(my_list)
ii = np.where(values == 5)[0]
print(ii)

[6]
[6]


 ### Problem 3: convert Pandas DataFrame into a Numpy array

In [5]:
df = pd.DataFrame(data={'A': [1, 2, 3],
                        'B': [4, 5, 6],
                        'C': [7, 8, 9]}, index=['a', 'b', 'c'])

# convert the entire dataframe
print(df.to_numpy())

# convert specific clms
print(df[['A', 'C']].to_numpy)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<bound method DataFrame.to_numpy of    A  C
a  1  7
b  2  8
c  3  9>


### Problem 4: calculate matrix mean

In [6]:
mylist = np.array(
    [[1, 2, 0],
     [0, 1, 1],
     [5, 6, 5]])

# print(mylist)

# calculate mean for clm values; for rows axis=1
clm_mean = mylist.mean(axis=0)
# print(clm_mean)

row_mean = mylist.mean(axis=1)
# print(row_mean)

# calculate mean of non-zero clm values
# clm_mean1 = np.true_divide(mylist.sum(0),(mylist!=0).sum(0))
# print(clm_mean1)

# replaces 0 with 100;
# mylist = np.where((mylist == 0),100,mylist)
# print(mylist)

#replaces 0 with mean;
# mylist = np.where((mylist == 0),mylist.mean(axis=0),mylist)
# # print(mylist)

# replaces 0 with non-zero mean of the clm values;
mylist = np.where((mylist == 0), np.true_divide(mylist.sum(0), (mylist != 0).sum(0)), mylist)
print(mylist)

[[1. 2. 3.]
 [3. 1. 1.]
 [5. 6. 5.]]


### Problem 5: matrix normalization 

In [7]:
mylist = np.array(
    [[1, 2, 0],
     [0, 1, 1],
     [5, 6, 5]])


# regular normalization
# norm = np.linalg.norm(mylist)

# #normalize the array
# norm_mylist = mylist/norm
# print(norm_mylist)

# mean of each clm
cmean = mylist.mean(axis=0)

#stdev of each clm
cstdev = np.std(mylist, axis=0)

#normalized matrix -- formula shared in the problem
result = (mylist-cmean)/cstdev
print(result)

#mean of each clm of the normalized matrix should be 0
print(result.mean(axis=0))

#std of each clm of the normalized matrix should be 1
print(np.std(result, axis=0))

[[-0.46291005 -0.46291005 -0.9258201 ]
 [-0.9258201  -0.9258201  -0.46291005]
 [ 1.38873015  1.38873015  1.38873015]]
[0. 0. 0.]
[1. 1. 1.]
